### PR TITLE
Fix file associate and double click of .ofx files.

### LINKED ISSUE #100: ofx file association stopped working with move to .NET 7
[5:18 PM] JP Duplessis (Guest)

Are you seeing the same problem:  I made sure that myMoney was associated to the QIF, QFX, OFX using the File item.
image

However double clicking on any downloaded QIF or OFX are not prompting MyMoney import. 

I have to do it manually by using File > Import

this use to work flawlessly for the last 10+ years

Also found a bug in the OFX import, here's the Ticket https://github.com/MoneyTools/MyMoney.Net/issues/98

### PR DESCRIPTION
**Pull request by clovett**
Fixes #100

### CODE REVIEW

File: Source/WPF/MyMoney/Ofx/Ofx.cs [hunk 1]
```diff
@@ -1736,9 +1736,19 @@ public XDocument ParseOfxResponse(Stream stm, bool implementSecurity)
                 }
             }
 
-
             // re-encode in the right encoding and read up to the starting <OFX> tag.
             stm.Seek(0, SeekOrigin.Begin);
+
+#if DEBUG_OFX_STREAM
```
Comment (jpdup) [inline Source/WPF/MyMoney/Ofx/Ofx.cs:1742]: Should not be part of this File Association fix right?

**Review by jpdup — COMMENTED** [review]
Remove that OFX debug code and Merge it in.  I can you this today :)

File: Source/WPF/MyMoney/Ofx/Ofx.cs (hunk 1 above)
Comment (jpdup) [reply Source/WPF/MyMoney/Ofx/Ofx.cs:1742]: Or keep the code since its behind a #If

**Comment by jpdup** [comment]
We are abandoning this PR, the solution does not "automatically" work and could introduce problem for non UTF-8 file

**Comment by jpdup** [comment]
Combined with the "Delete Registry Extension subkey" this works
